// src/App.js
import React, { useState, useEffect } from 'react';
import LengthControl from './LengthControl';
import Timer from './Timer';
import './App.css';

const App = () => {
  const [breakLength, setBreakLength] = useState(5);
    const [sessionLength, setSessionLength] = useState(25);
      const [timeLeft, setTimeLeft] = useState(25 * 60);
        const [timerLabel, setTimerLabel] = useState("Session");
          const [isRunning, setIsRunning] = useState(false);
            const [intervalId, setIntervalId] = useState(null);

              useEffect(() => {
                  if (timeLeft === 0) {
                        document.getElementById('beep').play();
                              if (timerLabel === "Session") {
                                      setTimerLabel("Break");
                                              setTimeLeft(breakLength * 60);
                                                    } else {
                                                            setTimerLabel("Session");
                                                                    setTimeLeft(sessionLength * 60);
                                                                          }
                                                                              }
                                                                                }, [timeLeft, timerLabel, breakLength, sessionLength]);

                                                                                  const handleBreakDecrement = () => {
                                                                                      if (breakLength > 1) {
                                                                                            setBreakLength(breakLength - 1);
                                                                                                }
                                                                                                  };

                                                                                                    const handleBreakIncrement = () => {
                                                                                                        if (breakLength < 60) {
                                                                                                              setBreakLength(breakLength + 1);
                                                                                                                  }
                                                                                                                    };

                                                                                                                      const handleSessionDecrement = () => {
                                                                                                                          if (sessionLength > 1) {
                                                                                                                                setSessionLength(sessionLength - 1);
                                                                                                                                      setTimeLeft((sessionLength - 1) * 60);
                                                                                                                                          }
                                                                                                                                            };

                                                                                                                                              const handleSessionIncrement = () => {
                                                                                                                                                  if (sessionLength < 60) {
                                                                                                                                                        setSessionLength(sessionLength + 1);
                                                                                                                                                              setTimeLeft((sessionLength + 1) * 60);
                                                                                                                                                                  }
                                                                                                                                                                    };

                                                                                                                                                                      const handleStartStop = () => {
                                                                                                                                                                          if (isRunning) {
                                                                                                                                                                                clearInterval(intervalId);
                                                                                                                                                                                      setIsRunning(false);
                                                                                                                                                                                          } else {
                                                                                                                                                                                                setIsRunning(true);
                                                                                                                                                                                                      const newIntervalId = setInterval(() => {
                                                                                                                                                                                                              setTimeLeft((prevTimeLeft) => prevTimeLeft - 1);
                                                                                                                                                                                                                    }, 1000);
                                                                                                                                                                                                                          setIntervalId(newIntervalId);
                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                  const handleReset = () => {
                                                                                                                                                                                                                                      clearInterval(intervalId);
                                                                                                                                                                                                                                          setIsRunning(false);
                                                                                                                                                                                                                                              setBreakLength(5);
                                                                                                                                                                                                                                                  setSessionLength(25);
                                                                                                                                                                                                                                                      setTimeLeft(25 * 60);
                                                                                                                                                                                                                                                          setTimerLabel("Session");
                                                                                                                                                                                                                                                              const beep = document.getElementById('beep');
                                                                                                                                                                                                                                                                  beep.pause();
                                                                                                                                                                                                                                                                      beep.currentTime = 0;
                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                              <div className="App">
                                                                                                                                                                                                                                                                                    <h1>25+5 CLOCK</h1>
                                                                                                                                                                                                                                                                                          <div className="length-controls">
                                                                                                                                                                                                                                                                                                  <LengthControl
                                                                                                                                                                                                                                                                                                            label="Break"
                                                                                                                                                                                                                                                                                                                      labelId="break-label"
                                                                                                                                                                                                                                                                                                                                decrementId="break-decrement"
                                                                                                                                                                                                                                                                                                                                          incrementId="break-increment"
                                                                                                                                                                                                                                                                                                                                                    lengthId="break-length"
                                                                                                                                                                                                                                                                                                                                                              length={breakLength}
                                                                                                                                                                                                                                                                                                                                                                        onDecrement={handleBreakDecrement}
                                                                                                                                                                                                                                                                                                                                                                                  onIncrement={handleBreakIncrement}
                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                  <LengthControl
                                                                                                                                                                                                                                                                                                                                                                                                            label="Session"
                                                                                                                                                                                                                                                                                                                                                                                                                      labelId="session-label"
                                                                                                                                                                                                                                                                                                                                                                                                                                decrementId="session-decrement"
                                                                                                                                                                                                                                                                                                                                                                                                                                          incrementId="session-increment"
                                                                                                                                                                                                                                                                                                                                                                                                                                                    lengthId="session-length"
                                                                                                                                                                                                                                                                                                                                                                                                                                                              length={sessionLength}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onDecrement={handleSessionDecrement}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onIncrement={handleSessionIncrement}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Timer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              timerLabel={timerLabel}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      timeLeft={timeLeft}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onStartStop={handleStartStop}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onReset={handleReset}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <audio id="beep" src="https://www.soundjay.com/button/beep-07.wav"></audio>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default App;

